# Generated by Django 5.2.7 on 2025-10-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('branch_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('bank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('branch_number', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bank.bankbranch')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLoans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Primary Borrower', 'Primary Borrower'), ('Co-borrower', 'Co-borrower'), ('Guarantor', 'Guarantor')], default='Primary Borrower', max_length=20)),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.loans')),
            ],
            options={
                'unique_together': {('customer', 'loan')},
            },
        ),
    ]
