# Generated by Django 5.2.7 on 2025-10-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bank_bankbranch_loans_customerloans'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_no', models.CharField(db_index=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_sync_queue',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(null=True)),
                ('old_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reconciliation_audit',
            },
        ),
        migrations.CreateModel(
            name='TransactionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField(null=True)),
                ('account_id', models.BigIntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('transaction_type', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction_audit',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
